stages:
  - build
  - deploy

variables:
  PUBLIC_URL: /${CI_PROJECT_NAME}

# Build and test job for all branches
build:
  stage: build
  image: node:20-alpine
  script:
    - npm ci
    - npm test || echo "No tests found, continuing with build"
    - cd docs
    - npm ci
    - npm run build
  artifacts:
    paths:
      - docs/out
  cache:
    paths:
      - node_modules
      - docs/node_modules

# Build job for all branches
build:
  stage: build
  image: node:20-alpine
  script:
    - cd docs
    - npm ci
    - npm run build
  artifacts:
    paths:
      - docs/out
  cache:
    paths:
      - docs/node_modules

# Deploy job for master branch
pages:
  stage: deploy
  image: node:20-alpine
  script:
    - cd docs
    - npm ci
    - npm run build
    - mkdir -p ../public
    - cp -r out/* ../public/
  artifacts:
    paths:
      - public
  only:
    - master

# Deploy job for PR branches
review:
  stage: deploy
  image: node:20-alpine
  script:
    - cd docs
    - npm ci
    - npm run build
    - mkdir -p ../public
    - cp -r out/* ../public/
  artifacts:
    paths:
      - public
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://${CI_PROJECT_NAMESPACE}.gitlab.io/-/${CI_PROJECT_NAME}/-/jobs/${CI_JOB_ID}/artifacts/public/index.html
  except:
    - master
