name: Build and Deploy Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      
      # Run tests in the repository
      - name: Run tests
        run: |
          # Install dependencies
          npm install
          
          # Run tests in src directory if it exists
          if [ -d "src" ]; then
            echo "Running tests in src directory"
            npm test
          else
            echo "No src directory found, checking for tests in other locations"
            # Try to find and run any test files in the repository
            find . -name "*.test.ts" -o -name "*.test.tsx" -o -name "*.spec.ts" -o -name "*.spec.tsx" | xargs -r npx vitest run
          fi
      
      - name: Build documentation site
        run: |
          cd docs
          npm ci
          npm run build
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: docs-build
          path: docs/out
  
  deploy:
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs-build
          path: ./public
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './public'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
